name: Quality Assurance Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      DATABASE_URL: postgresql://postgres:2608@localhost:5432/DBVECTOR
      JWT_SECRET: super_secret_key_change_me_123456
      FRONTEND_URL: http://localhost:5173
      TEST_USER_EMAIL: alejandro.marin@enel.com
      TEST_USER_PASS: 123456
      NODE_ENV: test
    
    services:
      postgres:
        image: ankane/pgvector
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: '2608'
          POSTGRES_DB: DBVECTOR
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install dependencies
        run: npm ci

      - name: Initialize Database Schema
        run: |
          # 1. Identificar dinámicamente el nombre del contenedor de postgres
          CONTAINER_NAME=$(docker ps --filter "ancestor=ankane/pgvector" --format "{{.Names}}")
          echo "Contenedor de DB detectado: $CONTAINER_NAME"
          
          # 2. Esperar a que Postgres esté disponible
          until pg_isready -h localhost -p 5432; do echo "Esperando a Postgres..."; sleep 2; done
          
          # 3. Inyectar el esquema usando el nombre dinámico y forzando UTF8
          docker exec -i $CONTAINER_NAME env PGCLIENTENCODING=UTF8 psql -U postgres -d DBVECTOR < src/db/init_schema.sql

      - name: Run Testing Suite
        run: npm test
